--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2024-06-04 23:21:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16512)
-- Name: brand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brand (
                              id integer NOT NULL,
                              name character varying(30) NOT NULL,
                              load_capacity numeric(5,2) NOT NULL,
                              fuel_tank_capacity numeric(6,2) NOT NULL,
                              seats_number smallint NOT NULL,
                              vehicle_type character varying(20) NOT NULL
);


ALTER TABLE public.brand OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16511)
-- Name: brand_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 241 (class 1259 OID 26031)
-- Name: car_mileage_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.car_mileage_report (
                                           id integer NOT NULL,
                                           vehicle_id integer
);


ALTER TABLE public.car_mileage_report OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 26030)
-- Name: carmileagereport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.car_mileage_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carmileagereport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 221 (class 1259 OID 16577)
-- Name: driver; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver (
                               id integer NOT NULL,
                               name character varying(30) NOT NULL,
                               salary numeric(20,2) NOT NULL,
                               age smallint NOT NULL,
                               experience smallint NOT NULL,
                               active boolean,
                               active_in_vehicle_id integer,
                               enterprise_id integer
);


ALTER TABLE public.driver OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16576)
-- Name: driver_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.driver ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 224 (class 1259 OID 16615)
-- Name: driver_vehicle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_vehicle (
                                       driver_id integer NOT NULL,
                                       vehicle_id integer NOT NULL
);


ALTER TABLE public.driver_vehicle OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16529)
-- Name: enterprise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enterprise (
                                   id integer NOT NULL,
                                   name character varying(100) NOT NULL,
                                   city character varying(100) NOT NULL,
                                   staff_number smallint NOT NULL,
                                   super_visor_name character varying(100) NOT NULL
);


ALTER TABLE public.enterprise OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16528)
-- Name: enterprise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enterprise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enterprise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 227 (class 1259 OID 16713)
-- Name: enterprise_manager; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enterprise_manager (
                                           enterprise_id integer NOT NULL,
                                           manager_id integer NOT NULL
);


ALTER TABLE public.enterprise_manager OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16706)
-- Name: manager; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.manager (
                                id integer NOT NULL,
                                username character varying(30) NOT NULL,
                                password character varying(100) NOT NULL
);


ALTER TABLE public.manager OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16705)
-- Name: manager_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.manager ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manager_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 239 (class 1259 OID 26023)
-- Name: report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report (
                               id integer NOT NULL,
                               name character varying(255),
                               period character varying(50),
                               start_date timestamp without time zone,
                               end_date timestamp without time zone,
                               result text
);


ALTER TABLE public.report OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 26022)
-- Name: report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 237 (class 1259 OID 26003)
-- Name: ride; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ride (
                             id integer NOT NULL,
                             vehicle_id integer,
                             start_date_time timestamp without time zone,
                             end_date_time timestamp without time zone,
                             distance numeric
);


ALTER TABLE public.ride OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 26002)
-- Name: ride_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ride ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 235 (class 1259 OID 25990)
-- Name: track; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.track (
                              id integer NOT NULL,
                              vehicle_id integer,
                              pt public.geometry(Point,4326),
                              created_at timestamp without time zone
);


ALTER TABLE public.track OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 25989)
-- Name: track_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 228 (class 1259 OID 24886)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              username character varying(10) NOT NULL,
                              password character varying(150) NOT NULL,
                              enabled boolean NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16599)
-- Name: vehicle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicle (
                                id integer NOT NULL,
                                year character varying(4) NOT NULL,
                                price numeric(20,2) NOT NULL,
                                mileage character varying(20),
                                brand_id integer,
                                enterprise_id integer,
                                purchase_date_time timestamp without time zone,
                                registration_number character varying
);


ALTER TABLE public.vehicle OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16598)
-- Name: vehicle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- TOC entry 5643 (class 2606 OID 16516)
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (id);


--
-- TOC entry 5671 (class 2606 OID 26035)
-- Name: car_mileage_report carmileagereport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_mileage_report
    ADD CONSTRAINT carmileagereport_pkey PRIMARY KEY (id);


--
-- TOC entry 5647 (class 2606 OID 16654)
-- Name: driver driver_active_in_vehicle_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_active_in_vehicle_id_key UNIQUE (active_in_vehicle_id);


--
-- TOC entry 5649 (class 2606 OID 16581)
-- Name: driver driver_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_pkey PRIMARY KEY (id);


--
-- TOC entry 5653 (class 2606 OID 16619)
-- Name: driver_vehicle driver_vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_vehicle
    ADD CONSTRAINT driver_vehicle_pkey PRIMARY KEY (driver_id, vehicle_id);


--
-- TOC entry 5659 (class 2606 OID 16717)
-- Name: enterprise_manager enterprise_manager_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enterprise_manager
    ADD CONSTRAINT enterprise_manager_pkey PRIMARY KEY (enterprise_id, manager_id);


--
-- TOC entry 5645 (class 2606 OID 16533)
-- Name: enterprise enterprise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enterprise
    ADD CONSTRAINT enterprise_pkey PRIMARY KEY (id);


--
-- TOC entry 5655 (class 2606 OID 16710)
-- Name: manager manager_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.manager
    ADD CONSTRAINT manager_pkey PRIMARY KEY (id);


--
-- TOC entry 5657 (class 2606 OID 16712)
-- Name: manager manager_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.manager
    ADD CONSTRAINT manager_username_key UNIQUE (username);


--
-- TOC entry 5669 (class 2606 OID 26029)
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (id);


--
-- TOC entry 5667 (class 2606 OID 26007)
-- Name: ride ride_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT ride_pkey PRIMARY KEY (id);


--
-- TOC entry 5665 (class 2606 OID 25996)
-- Name: track track_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT track_pkey PRIMARY KEY (id);


--
-- TOC entry 5661 (class 2606 OID 24890)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);


--
-- TOC entry 5651 (class 2606 OID 16603)
-- Name: vehicle vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_pkey PRIMARY KEY (id);


--
-- TOC entry 5682 (class 2606 OID 26036)
-- Name: car_mileage_report car_mileage_report_id_pk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_mileage_report
    ADD CONSTRAINT car_mileage_report_id_pk FOREIGN KEY (id) REFERENCES public.report(id);


--
-- TOC entry 5683 (class 2606 OID 26041)
-- Name: car_mileage_report carmileagereport_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_mileage_report
    ADD CONSTRAINT carmileagereport_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id);


--
-- TOC entry 5672 (class 2606 OID 16655)
-- Name: driver driver_active_in_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_active_in_vehicle_id_fkey FOREIGN KEY (active_in_vehicle_id) REFERENCES public.vehicle(id);


--
-- TOC entry 5673 (class 2606 OID 24857)
-- Name: driver driver_enterprise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprise(id) ON DELETE SET NULL;


--
-- TOC entry 5676 (class 2606 OID 16620)
-- Name: driver_vehicle driver_vehicle_driver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_vehicle
    ADD CONSTRAINT driver_vehicle_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver(id);


--
-- TOC entry 5677 (class 2606 OID 16625)
-- Name: driver_vehicle driver_vehicle_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_vehicle
    ADD CONSTRAINT driver_vehicle_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id);


--
-- TOC entry 5678 (class 2606 OID 16718)
-- Name: enterprise_manager enterprise_manager_enterprise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enterprise_manager
    ADD CONSTRAINT enterprise_manager_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprise(id);


--
-- TOC entry 5679 (class 2606 OID 16723)
-- Name: enterprise_manager enterprise_manager_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enterprise_manager
    ADD CONSTRAINT enterprise_manager_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.manager(id);


--
-- TOC entry 5681 (class 2606 OID 26008)
-- Name: ride ride_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT ride_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id) ON DELETE CASCADE;


--
-- TOC entry 5680 (class 2606 OID 25997)
-- Name: track track_vehicle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT track_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id) ON DELETE CASCADE;


--
-- TOC entry 5674 (class 2606 OID 16604)
-- Name: vehicle vehicle_brand_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.brand(id);


--
-- TOC entry 5675 (class 2606 OID 24852)
-- Name: vehicle vehicle_enterprise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_enterprise_id_fkey FOREIGN KEY (enterprise_id) REFERENCES public.enterprise(id) ON DELETE SET NULL;


-- Completed on 2024-06-04 23:21:35

--
-- PostgreSQL database dump complete
--

