name: Deploy Spring Boot Application with Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Build with Maven
          run: ./mvnw package

        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: autopark
            path: target/*.jar

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push App Docker Image
      run: |
        docker build -t autopark:${{ github.sha }} .
        docker push autopark:${{ github.sha }}

    - name: Build and Push DB Docker Image
      run: |
        docker build -t mydb:${{ github.sha }} ./db
        docker push mydb:${{ github.sha }}

    - name: Copy Docker Compose File
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "docker-compose.yml"
        target: "/path/to/server/"

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker-compose -f /path/to/server/docker-compose.yml pull
          docker-compose -f /path/to/server/docker-compose.yml up -d
